### ISSUE TITLE
Have you tried to add adapter on CLIP?

### ISSUE THREAD

**Issue by Rainlt** [codezakh/LilT#1]
hello, I'm interested in your pretty work and have some questions about the paper. I'm curious about that have you tried to add adapter on Clip, as the way you applied to bert-vit. 
The CLIP and bert-vit seem to have different pre-training data in table 1. As we know, original CLIP use 400M img-text pairs for training. Or does the CLIP in table 1 mean the bert-vit model which finetune all parameter actually?

More, why don't you fully finetune bert-vit on coco2014, and make it be the 100% trained version in table 1? I think such a model  may represent the 100% trained model more precisely than CLIP.

**Comment by codezakh** [comment]
Glad you're interested in the paper!

> Or does the CLIP in table 1 mean the bert-vit model which finetune all parameter actually?

Yes, this is what it means. For the experiments in the paper, we trained the bert-vit CLIP from scratch on 500k-4m pairs.

**Comment by Rainlt** [comment]
> Glad you're interested in the paper!
> 
> > Or does the CLIP in table 1 mean the bert-vit model which finetune all parameter actually?
> 
> Yes, this is what it means. For the experiments in the paper, we trained the bert-vit CLIP from scratch on 500k-4m pairs.

Thanks for your kind response!
